
set background=dark

" Bundles {

    source ~/.vim/bundles.vim

" }


" System {

    autocmd bufwritepost .vimrc source $MYVIMRC
    autocmd bufwritepost vimrc source $MYVIMRC

    set nocp
    filetype on
    filetype plugin on
    filetype indent on
    scriptencoding utf-8

    set history=1000
    set tags=./tags;/,~/.vimtags

    nnoremap <leader>b :Make<cr>

" }


" Searching {

    set incsearch
    set hlsearch 
    set ignorecase
    set smartcase
    nnoremap <c-c> :noh<cr><c-c>

" }


" Editing {

    set nowrap
    set tabstop=4
    set shiftwidth=4
    set expandtab
    set backspace=indent,eol,start
    set foldmethod=syntax
    set nofoldenable
    set undolevels=1000
    set pastetoggle=<F2>

    set wildmenu                    " show list instead of just completing
    set wildmode=list:longest,full  " command <Tab> completion, list matches, then longest common part, then all.

    set list
    set listchars=tab:,.,trail:.,extends:#,nbsp:. " Highlight problematic whitespace

" }


" Buffers {
    no <bs> <C-w>h
    no <C-h> <C-w>h
    no <C-j> <C-w>j
    no <C-k> <C-w>k
    no <C-l> <C-w>l

    set hidden

" }


" Styling {

    syntax enable
    set background=dark
    colorscheme wombat256i

    set showcmd
    set showmode
    set number

    set laststatus=2

    set guioptions-=m
    set guioptions-=T
    set guioptions-=r
    set guioptions-=R
    set guioptions-=l
    set guioptions-=L

" }


map <leader>f :NERDTreeToggle<cr>
let NERDTreeIgnore=['\.pyc', '\.beam', '\.o', '\~$', '\.swo$', '\.swp$', '\.git', '\.hg', '\.svn', '\.bzr']

map <leader>c :TagbarOpenAutoClose<cr>

let g:ctrlp_custom_ignore = { 
    \ 'dir':  'obj$\|build$\|ebin$\|\.git$\|\.hg$\|\.svn$\|deps$\|_build$\|node_modules$\|bower_components$\|vendor$\|tmp$\|dist$',
    \ 'file': '\.beam$\|\.exe$\|\.so$\|\.dll$\|\.o$' } 

let g:ack_use_dispatch=1

let g:airline_powerline_fonts = 1
let g:ctrlp_show_hidden = 1

let g:ycm_key_list_select_completion = ['<C-n>', '<Down>']
let g:ycm_key_list_previous_completion = ['<C-p>', '<Up>']
let g:SuperTabDefaultCompletionType = '<C-n>'

let g:UltiSnipsUsePythonVersion = 2
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"
let g:UltiSnipsEditSplit="vertical"

let g:ycm_enable_diagnostic_signs = 0
let g:ycm_enable_diagnostic_highlighting = 0

nnoremap <leader>jd :YcmCompleter GoTo<CR>

set completeopt-=preview

map <LEADER>t :!ctags -R --c++-kinds=+plx --fields=+iaS --extra=+q .<CR>
